# Source - https://stackoverflow.com/a/70992127
# Posted by ThrowsError, modified by community. See post 'Timeline' for change history
# Retrieved 2026-03-09, License - CC BY-SA 4.0

name: Deploy Javadoc

on:
  push:
    branches:
      - stable
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: stable
          java-version: 17
          target-folder: javadoc 
